######################################################################
# Automatically generated by qmake (3.0) Wed Jul 5 20:32:40 2017
######################################################################

TEMPLATE = app
TARGET = ws2812
INCLUDEPATH += .

# Input
SOURCES += ws2812.c

HEADERS += \
    ws2812.h
